project:
  type: website

website:
  title: "STML2022"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/guebin/STML2022/tree/main/posts
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true